import { auth, db, companyCollection, companyDoc, getCompanyId } from "../Js/firebase.js";
import { loadSession } from "./companySession.js";
import { canManageDevices, isCompanyAdmin, hasPermission } from "./permissions.js";
import { onAuthStateChanged } from "https://www.gstatic.com/firebasejs/11.10.0/firebase-auth.js";
import { collection, doc, getDocs, getDoc, updateDoc, setDoc, query, where, limit, serverTimestamp, onSnapshot } from "https://www.gstatic.com/firebasejs/11.10.0/firebase-firestore.js";

const safe=v=>String(v??"").replace(/[&<>'"]/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;","'":"&#39;",'"':"&quot;"}[c]));
const fmt=v=>v?.toDate?.()?.toLocaleString?.()||(v?new Date(v).toLocaleString():"—");
const arr=v=>Array.isArray(v)?v:[];
let session=null;
let customerRealtimeTimer=null;
let unsubscribe=[];

function toast(message,error=false){
  let x=document.getElementById("nlCustomerToast");
  if(!x){x=document.createElement("div");x.id="nlCustomerToast";document.body.appendChild(x)}
  x.textContent=message;x.className=`nl-customer-toast show ${error?'error':''}`;
  clearTimeout(x._t);x._t=setTimeout(()=>x.className="nl-customer-toast",3200);
}

async function audit(action,entity,entityId="",metadata={}){
  try{await setDoc(companyDoc(companyCollection(db,"auditLogs")),{companyId:getCompanyId(),action,entity,entityId,metadata,performedBy:auth.currentUser?.uid||"",performedByEmail:auth.currentUser?.email||"",createdAt:serverTimestamp()})}catch(e){console.warn("NEWLOOK audit event unavailable",e)}
}

function addMenu(id,label,icon){
  const menu=document.querySelector(".menu");
  if(!menu)return null;
  const existing=menu.querySelector(`[data-section="${id}"]`);if(existing)return existing;
  const li=document.createElement("li");li.dataset.section=id;li.innerHTML=`<i class="fas fa-${icon}"></i> ${label}`;menu.appendChild(li);li.addEventListener("click",()=>show(id));return li;
}
function addPage(id,title,subtitle,html){
  const main=document.querySelector(".main");if(!main)return null;
  if(document.getElementById(id))return document.getElementById(id);
  const s=document.createElement("section");s.id=id;s.className="page nl-customer-page";s.innerHTML=`<header class="nl-customer-header"><div><span>NEWLOOK SaaS</span><h1>${safe(title)}</h1><p>${safe(subtitle)}</p></div></header>${html}`;main.appendChild(s);return s;
}
function show(id){
  document.querySelectorAll(".menu li").forEach(x=>x.classList.toggle("active",x.dataset.section===id));
  document.querySelectorAll(".page").forEach(x=>x.classList.toggle("active-page",x.id===id));
  if(id==='devices')loadDevices(); if(id==='notifications')loadNotifications(); if(id==='support')loadTickets(); if(id==='settings')loadSettings(); if(id==='users')loadUsers(); if(id==='operations')loadOperations(); if(id==='documents')loadDocuments(); if(id==='reports')loadReports(); if(id==='analytics')loadAnalytics();
}
async function readCollection(name,n=300){try{return (await getDocs(query(companyCollection(db,name),limit(n)))).docs.map(d=>({id:d.id,...d.data()}));}catch(e){console.warn(`NEWLOOK read ${name}`,e);return []}}

function buildNavigation(){
  if(!session?.role)return;
  const defs=[['devices','Device Management','mobile-alt','devices'],['notifications','Notifications','bell','notifications'],['support','Support','life-ring','support'],['users','Users & Access','users','users'],['operations','Operations Control','gauge-high','operations'],['payroll','Payroll','file-invoice-dollar','payroll'],['documents','Documents','folder-open','documents'],['settings','Company Settings','sliders','settings']];
  defs.forEach(([id,label,icon,permission])=>{if(hasPermission(session.role,permission))addMenu(id,label,icon)});
}

function appendToExisting(id,html){const s=document.getElementById(id);if(!s||s.querySelector(`[data-newlook-enterprise="${id}"]`))return;const box=document.createElement("div");box.dataset.newlookEnterprise=id;box.innerHTML=html;s.appendChild(box)}

function buildPages(){
  if(!session?.role)return;
  if(hasPermission(session.role,'devices'))addPage('devices','Device Management','Register, activate, revoke and monitor company Guard and Attendance devices.',`<div class="nl-card-grid"><div class="nl-card"><div class="nl-card-title">Device lifecycle</div><p>Every device is registered under this company and can only operate against its tenant context.</p><div class="nl-actions"><button class="action-btn action-btn-primary" id="nlRegisterDevice">Register Device</button><button class="action-btn action-btn-secondary" id="nlRefreshDevices">Refresh</button></div></div><div class="nl-card" id="nlDeviceSummary">Loading…</div></div><div class="nl-table-wrap"><table><thead><tr><th>Device</th><th>Type</th><th>Site</th><th>Status</th><th>Registered</th><th>Actions</th></tr></thead><tbody id="nlDeviceBody"></tbody></table></div>`);
  if(hasPermission(session.role,'notifications'))addPage('notifications','Notifications','Company announcements, security alerts, billing notices and support updates.',`<div class="nl-card"><div class="nl-actions"><button class="action-btn action-btn-secondary" id="nlRefreshNotifications">Refresh</button><button class="action-btn action-btn-secondary" id="nlMarkAll">Mark all read</button></div><div id="nlNotificationList"></div></div>`);
  if(hasPermission(session.role,'support'))addPage('support','Support','Open, follow and track requests with the NEWLOOK platform team.',`<div class="nl-card"><div class="nl-form-grid"><label>Subject<input id="nlSupportSubject" maxlength="120"></label><label>Priority<select id="nlSupportPriority"><option value="normal">Normal</option><option value="high">High</option><option value="urgent">Urgent</option></select></label><label class="wide">Message<textarea id="nlSupportMessage" maxlength="4000"></textarea></label></div><div class="nl-actions"><button class="action-btn action-btn-primary" id="nlCreateTicket">Create Ticket</button><button class="action-btn action-btn-secondary" id="nlRefreshTickets">Refresh</button></div></div><div id="nlTicketList"></div>`);
  if(hasPermission(session.role,'users'))addPage('users','Users & Access','Company-scoped identity, roles and access.',`<div class="nl-card-grid"><div class="nl-card"><div class="nl-card-title">Company identity source</div><p>Authenticated users come from <strong>users/{uid}</strong> and are tenant-scoped by <strong>companyId</strong>.</p><div class="nl-actions"><a class="action-btn action-btn-primary" href="company-users.html" style="display:inline-block;text-decoration:none">Open Team Access</a><button class="action-btn action-btn-secondary" id="nlRefreshUsers">Refresh</button></div></div><div class="nl-card" id="nlUserSummary">Loading…</div></div><div id="nlUserList"></div>`);
  if(hasPermission(session.role,'operations'))addPage('operations','Operations Control','Live company-wide operational control without mixing payroll source records.',`<div id="nlOperationsBody"></div>`);
  if(hasPermission(session.role,'payroll'))addPage('payroll','Payroll','Dedicated enterprise payroll environment.',`<div class="nl-card-grid"><div class="nl-card"><div class="nl-card-title">Enterprise Payroll</div><p><strong>shiftRecords</strong> remains Security Payroll and <strong>attendanceRecords</strong> remains Staff Payroll. Payroll processing remains isolated from operational collections.</p><div class="nl-actions"><a class="action-btn action-btn-primary" href="payroll.html" style="display:inline-block;text-decoration:none">Open Payroll</a></div></div></div>`);
  if(hasPermission(session.role,'documents'))addPage('documents','Documents','Company document registry with tenant-scoped metadata and lifecycle.',`<div class="nl-card"><div class="nl-form-grid"><label>Document name<input id="nlDocName" maxlength="160"></label><label>Document type<input id="nlDocType" maxlength="80" placeholder="Policy, contract, compliance…"></label><label>Status<select id="nlDocStatus"><option value="active">Active</option><option value="draft">Draft</option><option value="expired">Expired</option><option value="archived">Archived</option></select></label><label>Reference<input id="nlDocReference" maxlength="120"></label><label class="wide">Notes<textarea id="nlDocNotes" maxlength="2000"></textarea></label></div><div class="nl-actions"><button class="action-btn action-btn-primary" id="nlSaveDocument">Save Document</button><button class="action-btn action-btn-secondary" id="nlClearDocument">Clear</button><button class="action-btn action-btn-secondary" id="nlRefreshDocuments">Refresh</button></div></div><div id="nlDocumentList"></div>`);
  if(hasPermission(session.role,'settings'))addPage('settings','Company Settings','Maintain the company identity and permitted tenant configuration.',`<div class="nl-card"><div class="nl-form-grid"><label>Company name<input id="nlCompanyName"></label><label>Contact email<input id="nlCompanyEmail" type="email"></label><label>Phone<input id="nlCompanyPhone"></label><label>Address<input id="nlCompanyAddress"></label></div><div class="nl-actions"><button class="action-btn action-btn-primary" id="nlSaveSettings">Save Settings</button><button class="action-btn action-btn-secondary" id="nlReloadSettings">Reload</button></div></div><div class="nl-card" id="nlPlanCard"></div>`);
  if(hasPermission(session.role,'reports'))appendToExisting('reports',`<div class="nl-card"><div class="nl-card-title">Company Reports Center</div><p>Generate tenant-scoped operational snapshots from the existing company collections.</p><div class="nl-form-grid"><label>Report<select id="nlReportType"><option value="operations">Operations Summary</option><option value="guards">Guard Register</option><option value="sites">Site Register</option><option value="attendance">Attendance Summary</option><option value="patrols">Patrol Summary</option><option value="visitors">Visitor Summary</option><option value="incidents">Incident Summary</option><option value="panicAlerts">Panic Alert Summary</option><option value="payroll">Payroll Summary</option><option value="securityPayroll">Security Payroll Source</option><option value="staffPayroll">Staff Payroll Source</option></select></label><label>Output<select id="nlReportOutput"><option value="screen">Screen</option><option value="csv">CSV</option><option value="print">Print</option></select></label></div><div class="nl-actions"><button class="action-btn action-btn-primary" id="nlGenerateReport">Generate Report</button></div><div id="nlReportResult"></div></div>`);
  if(hasPermission(session.role,'analytics'))appendToExisting('analytics',`<div class="nl-card"><div class="nl-card-title">Company Analytics</div><p>Calculated from this company's operational collections only.</p><div id="nlAnalyticsGrid" class="nl-analytics-grid"></div><div id="nlAnalyticsDetail"></div><div class="nl-actions"><button class="action-btn action-btn-secondary" id="nlRefreshAnalytics">Refresh Analytics</button></div></div>`);
}

async function loadDevices(){const body=document.getElementById('nlDeviceBody');if(!body)return;try{const s=await getDocs(companyCollection(db,'devices'));let active=0,guard=0,attendance=0;body.innerHTML=s.docs.map(d=>{const x=d.data(),type=String(x.deviceType||'guard').toLowerCase();if(String(x.status).toLowerCase()==='active')active++;if(type==='guard')guard++;if(type==='attendance')attendance++;return `<tr><td><strong>${safe(x.deviceName||'NEWLOOK Device')}</strong><small>${safe(x.authUid||d.id)}</small></td><td>${safe(type)}</td><td>${safe(x.siteName||x.siteId||'—')}</td><td><span class="nl-pill ${safe(String(x.status||'unknown').toLowerCase())}">${safe(x.status||'unknown')}</span></td><td>${safe(fmt(x.registeredAt))}</td><td>${canManageDevices(session.role)?`<button class="action-btn ${String(x.status).toLowerCase()==='active'?'action-btn-danger':'action-btn-success'} nl-device-toggle" data-id="${safe(d.id)}" data-next="${String(x.status).toLowerCase()==='active'?'revoked':'active'}">${String(x.status).toLowerCase()==='active'?'Revoke':'Activate'}</button>`:'View only'}</td></tr>`}).join('')||'<tr><td colspan="6" class="nl-empty">No devices registered.</td></tr>';document.getElementById('nlDeviceSummary').innerHTML=`<div class="nl-card-title">Fleet status</div><div class="nl-stats"><b>${active}<small>Active</small></b><b>${guard}<small>Guard</small></b><b>${attendance}<small>Attendance</small></b></div>`;body.querySelectorAll('.nl-device-toggle').forEach(b=>b.onclick=async()=>{if(!confirm(`${b.dataset.next==='revoked'?'Revoke':'Activate'} this device?`))return;try{await updateDoc(doc(db,'companies',getCompanyId(),'devices',b.dataset.id),{status:b.dataset.next,updatedAt:serverTimestamp()});await audit('DEVICE_STATUS_CHANGED','device',b.dataset.id,{status:b.dataset.next});toast('Device updated');loadDevices()}catch(e){toast(e.message,true)}})}catch(e){body.innerHTML=`<tr><td colspan="6">${safe(e.message)}</td></tr>`}}

async function loadNotifications(){const box=document.getElementById('nlNotificationList');if(!box)return;try{const rows=await readCollection('notifications',80);rows.sort((a,b)=>String(b.createdAt?.toMillis?.()||b.createdAt||0).localeCompare(String(a.createdAt?.toMillis?.()||a.createdAt||0)));box.innerHTML=rows.map(x=>{const read=Boolean(x.read||x.readBy?.[auth.currentUser?.uid]);return `<article class="nl-notification ${read?'read':''}"><div><strong>${safe(x.title||'Notification')}</strong><p>${safe(x.message||'')}</p><small>${safe(x.type||'info')} · ${safe(fmt(x.createdAt))}</small></div>${read?'':`<button class="action-btn action-btn-secondary nl-read" data-id="${safe(x.id)}">Mark read</button>`}</article>`}).join('')||'<div class="nl-empty">No notifications.</div>';box.querySelectorAll('.nl-read').forEach(b=>b.onclick=async()=>{try{await updateDoc(doc(db,'companies',getCompanyId(),'notifications',b.dataset.id),{[`readBy.${auth.currentUser.uid}`]:true,updatedAt:serverTimestamp()});loadNotifications()}catch(e){toast(e.message,true)}})}catch(e){box.innerHTML=`<div class="nl-empty">${safe(e.message)}</div>`}}

async function loadTickets(){const box=document.getElementById('nlTicketList');if(!box)return;try{const rows=await readCollection('supportTickets',50);rows.sort((a,b)=>String(b.createdAt?.toMillis?.()||b.createdAt||0).localeCompare(String(a.createdAt?.toMillis?.()||a.createdAt||0)));box.innerHTML=rows.map(x=>`<article class="nl-ticket"><div class="nl-ticket-head"><strong>${safe(x.subject||'Untitled')}</strong><span>${safe(x.status||'open')}</span><span>${safe(x.priority||'normal')}</span></div><p>${safe(x.message||'')}</p>${x.response?`<div class="nl-response"><strong>NEWLOOK Support</strong><p>${safe(x.response)}</p><small>${safe(fmt(x.respondedAt))}</small></div>`:''}<small>Created ${safe(fmt(x.createdAt))}</small>${x.createdBy===auth.currentUser?.uid&&String(x.status||'').toLowerCase()!=='closed'?`<button class="action-btn action-btn-secondary nl-follow" data-id="${safe(x.id)}">Add follow-up</button>`:''}</article>`).join('')||'<div class="nl-empty">No support tickets.</div>';box.querySelectorAll('.nl-follow').forEach(b=>b.onclick=async()=>{const message=prompt('Add follow-up message');if(!message?.trim())return;try{const old=rows.find(x=>x.id===b.dataset.id)?.message||'';await updateDoc(doc(db,'companies',getCompanyId(),'supportTickets',b.dataset.id),{message:`${old}\n\nFollow-up: ${message.trim()}`,updatedAt:serverTimestamp()});await audit('SUPPORT_FOLLOW_UP','supportTicket',b.dataset.id);loadTickets()}catch(e){toast(e.message,true)}})}catch(e){box.innerHTML=`<div class="nl-empty">${safe(e.message)}</div>`}}

async function createTicket(){const subject=document.getElementById('nlSupportSubject')?.value.trim(),message=document.getElementById('nlSupportMessage')?.value.trim(),priority=document.getElementById('nlSupportPriority')?.value||'normal';if(!subject||!message)return toast('Enter a subject and message.',true);try{const r=companyDoc(companyCollection(db,'supportTickets'));await setDoc(r,{ticketId:r.id,companyId:getCompanyId(),companyName:session.companyName||'',subject,message,priority,status:'open',createdBy:auth.currentUser.uid,createdByEmail:auth.currentUser.email||'',createdAt:serverTimestamp(),updatedAt:serverTimestamp()});await audit('SUPPORT_TICKET_CREATED','supportTicket',r.id,{priority});toast('Support ticket created');document.getElementById('nlSupportSubject').value='';document.getElementById('nlSupportMessage').value='';loadTickets()}catch(e){toast(e.message,true)}}

async function loadUsers(){const box=document.getElementById('nlUserList');if(!box)return;try{const snap=await getDocs(query(collection(db,'users'),where('companyId','==',getCompanyId()),limit(200)));const scoped=snap.docs.map(d=>({id:d.id,...d.data()}));const active=scoped.filter(x=>String(x.status||'active').toLowerCase()==='active').length;document.getElementById('nlUserSummary').innerHTML=`<div class="nl-card-title">Access summary</div><div class="nl-stats"><b>${scoped.length}<small>Users</small></b><b>${active}<small>Active</small></b><b>${Math.max(0,scoped.length-active)}<small>Inactive</small></b></div>`;box.innerHTML=scoped.length?`<div class="nl-table-wrap"><table><thead><tr><th>Name</th><th>Email</th><th>Role</th><th>Status</th></tr></thead><tbody>${scoped.map(x=>`<tr><td>${safe(x.fullName||x.displayName||'—')}</td><td>${safe(x.email||'—')}</td><td>${safe(x.role||'—')}</td><td>${safe(x.status||'active')}</td></tr>`).join('')}</tbody></table></div>`:'<div class="nl-card"><p>No company users found.</p></div>'}catch(e){box.innerHTML=`<div class="nl-card"><p>${safe(e.message)}</p></div>`}}

async function loadOperations(){const box=document.getElementById('nlOperationsBody');if(!box)return;const names=['guards','sites','shifts','attendance','patrols','visitors','incidents','panicAlerts'];try{const data=await Promise.all(names.map(n=>readCollection(n,300)));const labels=['Guards','Sites','Shifts','Attendance','Patrols','Visitors','Incidents','Panic alerts'];box.innerHTML=`<section class="nl-enterprise-grid">${data.map((x,i)=>`<div class="nl-card metric"><div class="label">${labels[i]}</div><div class="value">${x.length}</div><small>Company scoped</small></div>`).join('')}</section><section class="nl-card"><h3>Operational control</h3><p>Payroll source collections are intentionally excluded. This control view aggregates only operational company data.</p></section>`}catch(e){box.innerHTML=`<div class="nl-card"><p>${safe(e.message)}</p></div>`}}

async function loadDocuments(){const box=document.getElementById('nlDocumentList');if(!box)return;try{const rows=await readCollection('documents',200);box.innerHTML=rows.length?`<div class="nl-table-wrap"><table><thead><tr><th>Document</th><th>Type</th><th>Reference</th><th>Status</th><th>Updated</th><th>Action</th></tr></thead><tbody>${rows.map(x=>`<tr><td><strong>${safe(x.name||x.title||x.fileName||x.id)}</strong><small>${safe(x.notes||'')}</small></td><td>${safe(x.type||'document')}</td><td>${safe(x.reference||'—')}</td><td>${safe(x.status||'active')}</td><td>${safe(fmt(x.updatedAt||x.createdAt))}</td><td>${isCompanyAdmin(session.role)?`<button class="action-btn action-btn-danger nl-doc-delete" data-id="${safe(x.id)}">Delete</button>`:'View only'}</td></tr>`).join('')}</tbody></table></div>`:'<div class="nl-card"><p>No company documents found.</p></div>';box.querySelectorAll('.nl-doc-delete').forEach(b=>b.onclick=async()=>{if(!confirm('Delete this company document record?'))return;try{await import('https://www.gstatic.com/firebasejs/11.10.0/firebase-firestore.js').then(({deleteDoc})=>deleteDoc(doc(db,'companies',getCompanyId(),'documents',b.dataset.id)));await audit('DOCUMENT_DELETED','document',b.dataset.id);toast('Document deleted');loadDocuments()}catch(e){toast(e.message,true)}})}catch(e){box.innerHTML=`<div class="nl-card"><p>${safe(e.message)}</p></div>`}}

async function saveDocument(){if(!isCompanyAdmin(session.role))return toast('Only Company Administrators can save documents.',true);const name=document.getElementById('nlDocName')?.value.trim(),type=document.getElementById('nlDocType')?.value.trim()||'document',status=document.getElementById('nlDocStatus')?.value||'active',reference=document.getElementById('nlDocReference')?.value.trim(),notes=document.getElementById('nlDocNotes')?.value.trim();if(!name)return toast('Enter a document name.',true);try{const r=companyDoc(companyCollection(db,'documents'));await setDoc(r,{documentId:r.id,companyId:getCompanyId(),name,type,status,reference,notes,createdBy:auth.currentUser.uid,createdAt:serverTimestamp(),updatedAt:serverTimestamp()});await audit('DOCUMENT_CREATED','document',r.id,{type,status});toast('Document record saved');['nlDocName','nlDocType','nlDocReference','nlDocNotes'].forEach(id=>{const e=document.getElementById(id);if(e)e.value=''});loadDocuments()}catch(e){toast(e.message,true)}}

async function loadSettings(){if(!isCompanyAdmin(session.role))return;try{const snap=await getDoc(doc(db,'companies',getCompanyId()));if(!snap.exists())throw new Error('Company account not found.');const x=snap.data();document.getElementById('nlCompanyName').value=x.name||x.companyName||'';document.getElementById('nlCompanyEmail').value=x.contactEmail||x.email||'';document.getElementById('nlCompanyPhone').value=x.phone||'';document.getElementById('nlCompanyAddress').value=x.address||'';document.getElementById('nlPlanCard').innerHTML=`<div class="nl-card-title">Current subscription</div><p><strong>${safe(x.planId||'Not assigned')}</strong> · ${safe(x.subscriptionStatus||'unknown')}</p><small>Expires: ${safe(fmt(x.subscriptionEndsAt))}</small>`}catch(e){toast(e.message,true)}}
async function saveSettings(){if(!isCompanyAdmin(session.role))return toast('Only Company Administrators can save company settings.',true);try{const name=document.getElementById('nlCompanyName').value.trim(),contactEmail=document.getElementById('nlCompanyEmail').value.trim(),phone=document.getElementById('nlCompanyPhone').value.trim(),address=document.getElementById('nlCompanyAddress').value.trim();if(!name)return toast('Company name is required.',true);await updateDoc(doc(db,'companies',getCompanyId()),{name,companyName:name,contactEmail,phone,address,updatedAt:serverTimestamp()});await audit('COMPANY_SETTINGS_UPDATED','company',getCompanyId(),{fields:['name','contactEmail','phone','address']});toast('Company settings saved');await loadSettings()}catch(e){toast(e.message,true)}}

async function loadReports(){const r=document.getElementById('nlReportResult');if(r)r.innerHTML='<div class="nl-empty">Choose a report and generate it. Data is read only from this company tenant.</div>'}
async function generateReport(){const type=document.getElementById('nlReportType')?.value||'operations',output=document.getElementById('nlReportOutput')?.value||'screen',box=document.getElementById('nlReportResult');if(!box)return;const sourceMap={operations:['guards','sites','shifts','attendance','patrols','visitors','incidents','panicAlerts'],guards:['guards'],sites:['sites'],attendance:['attendance'],patrols:['patrols'],visitors:['visitors'],incidents:['incidents'],panicAlerts:['panicAlerts'],payroll:['payroll'],securityPayroll:['shiftRecords'],staffPayroll:['attendanceRecords']};const names=sourceMap[type]||['guards'];const rows=await Promise.all(names.map(n=>readCollection(n,1000)));let data=[];if(type==='operations'){data=[['Metric','Count'],...names.map((n,i)=>[n,rows[i].length])]}else{const raw=rows[0];const keys=[...new Set(raw.flatMap(x=>Object.keys(x).filter(k=>!['companyId','faceDescriptor','photoBase64'].includes(k))))];data=[keys,...raw.map(x=>keys.map(k=>{const v=x[k];return v?.toDate?.()?.toISOString?.()??(typeof v==='object'?'':v??'')}))];}const html=type==='operations'?`<table class="nl-report-table"><thead><tr><th>Metric</th><th>Count</th></tr></thead><tbody>${data.slice(1).map(r=>`<tr><td>${safe(r[0])}</td><td>${safe(r[1])}</td></tr>`).join('')}</tbody></table>`:`<div class="nl-table-wrap"><table class="nl-report-table"><thead><tr>${(data[0]||['Record']).map(k=>`<th>${safe(k)}</th>`).join('')}</tr></thead><tbody>${data.length>1?data.slice(1,301).map(x=>`<tr>${x.map(v=>`<td>${safe(v)}</td>`).join('')}</tr>`).join(''):`<tr><td colspan="${data[0]?.length||1}" class="nl-empty">No records.</td></tr>`}</tbody></table></div>`;box.innerHTML=`<div class="nl-card"><strong>${safe(type)} report</strong><p>Company: ${safe(session.companyName)} · Generated: ${safe(new Date().toLocaleString())}</p>${html}</div>`;await audit('REPORT_GENERATED','report',type,{output,recordCount:type==='operations'?data.length-1:Math.max(0,data.length-1),sourceCollections:names});if(output==='print'){const w=window.open('','_blank');if(w){w.document.write(`<html><head><title>NEWLOOK ${safe(type)} Report</title></head><body>${box.innerHTML}</body></html>`);w.document.close();w.print()}}if(output==='csv'){const csv=data.map(row=>row.map(v=>`"${String(v??'').replace(/"/g,'""')}"`).join(',')).join('\n');const blob=new Blob([csv],{type:'text/csv;charset=utf-8'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=`NEWLOOK_${type}_${getCompanyId()}_${new Date().toISOString().slice(0,10)}.csv`;a.click();URL.revokeObjectURL(a.href)}}

async function loadAnalytics(){const grid=document.getElementById('nlAnalyticsGrid');if(!grid)return;const [guards,sites,shifts,attendance,patrols,visitors,incidents,panicAlerts]=await Promise.all(['guards','sites','shifts','attendance','patrols','visitors','incidents','panicAlerts'].map(n=>readCollection(n,1000)));const activeGuards=guards.filter(x=>['active','on duty'].includes(String(x.status||'').toLowerCase())).length;const openIncidents=incidents.filter(x=>!['resolved','closed'].includes(String(x.status||'').toLowerCase())).length;const activePanic=panicAlerts.filter(x=>['active','open'].includes(String(x.status||'').toLowerCase())).length;grid.innerHTML=[['Guards',guards.length],['Active guards',activeGuards],['Sites',sites.length],['Shifts',shifts.length],['Attendance records',attendance.length],['Patrol records',patrols.length],['Visitors',visitors.length],['Open incidents',openIncidents],['Active panic',activePanic]].map(([l,v])=>`<div class="nl-card metric"><div class="label">${safe(l)}</div><div class="value">${safe(v)}</div><small>Tenant scoped</small></div>`).join('');document.getElementById('nlAnalyticsDetail').innerHTML=`<p class="nl-analytics-note">Analytics are calculated from the company's operational records at refresh time. Payroll source records are excluded from this dashboard.</p>`}

function wire(){document.getElementById('nlRegisterDevice')?.addEventListener('click',()=>location.href='device-registration.html');document.getElementById('nlRefreshDevices')?.addEventListener('click',loadDevices);document.getElementById('nlRefreshNotifications')?.addEventListener('click',loadNotifications);document.getElementById('nlMarkAll')?.addEventListener('click',async()=>{try{const s=await getDocs(query(companyCollection(db,'notifications'),limit(80)));await Promise.all(s.docs.filter(d=>!d.data().readBy?.[auth.currentUser.uid]&&!d.data().read).map(d=>updateDoc(d.ref,{[`readBy.${auth.currentUser.uid}`]:true,updatedAt:serverTimestamp()})));await audit('NOTIFICATIONS_MARKED_READ','notification','all');loadNotifications()}catch(e){toast(e.message,true)}});document.getElementById('nlCreateTicket')?.addEventListener('click',createTicket);document.getElementById('nlRefreshTickets')?.addEventListener('click',loadTickets);document.getElementById('nlRefreshUsers')?.addEventListener('click',loadUsers);document.getElementById('nlSaveDocument')?.addEventListener('click',saveDocument);document.getElementById('nlClearDocument')?.addEventListener('click',()=>['nlDocName','nlDocType','nlDocReference','nlDocNotes'].forEach(id=>{const e=document.getElementById(id);if(e)e.value=''}));document.getElementById('nlRefreshDocuments')?.addEventListener('click',loadDocuments);document.getElementById('nlSaveSettings')?.addEventListener('click',saveSettings);document.getElementById('nlReloadSettings')?.addEventListener('click',loadSettings);document.getElementById('nlGenerateReport')?.addEventListener('click',generateReport);document.getElementById('nlRefreshAnalytics')?.addEventListener('click',loadAnalytics)}

function startRealtime(){unsubscribe.forEach(fn=>{try{fn()}catch{}});unsubscribe=[];const names=['devices','notifications','supportTickets','documents','guards','sites','shifts','attendance','patrols','visitors','incidents','panicAlerts'];names.forEach(name=>{try{unsubscribe.push(onSnapshot(companyCollection(db,name),()=>{const id=document.querySelector('.page.active-page')?.id;if(id==='devices'&&name==='devices')loadDevices();if(id==='notifications'&&name==='notifications')loadNotifications();if(id==='support'&&name==='supportTickets')loadTickets();if(id==='documents'&&name==='documents')loadDocuments();if(id==='operations'&&['guards','sites','shifts','attendance','patrols','visitors','incidents','panicAlerts'].includes(name))loadOperations();if(id==='analytics'&&['guards','sites','shifts','attendance','patrols','visitors','incidents','panicAlerts'].includes(name))loadAnalytics();}));}catch(e){console.warn(`NEWLOOK realtime ${name}`,e)}})}
function startCustomerAutoRefresh(){if(customerRealtimeTimer)clearInterval(customerRealtimeTimer);customerRealtimeTimer=setInterval(()=>{if(document.hidden||!session?.companyId)return;const id=document.querySelector('.page.active-page')?.id;if(id==='devices')loadDevices();if(id==='notifications')loadNotifications();if(id==='support')loadTickets();if(id==='users')loadUsers();if(id==='operations')loadOperations();if(id==='documents')loadDocuments();if(id==='settings')loadSettings();if(id==='analytics')loadAnalytics();window.NEWLOOK_CUSTOMER_LAST_REFRESH=new Date().toISOString()},30000);window.NEWLOOK_CUSTOMER_AUTO_REFRESH=true}

onAuthStateChanged(auth,async user=>{if(!user)return;try{session=await loadSession(user);if(!session.companyId)return;window.currentUser=session;buildNavigation();buildPages();wire();startRealtime();startCustomerAutoRefresh();window.NEWLOOK_CUSTOMER_TOOLS={showSection:show,loadDevices,loadNotifications,loadTickets,loadUsers,loadOperations,loadDocuments,loadSettings,loadReports,loadAnalytics,generateReport}}catch(e){console.error('Customer SaaS control',e)}});
