import { auth, db, companyCollection, companyDoc, getCompanyId } from "../Js/firebase.js";
import { loadSession } from "./companySession.js";
import { canManageDevices, isCompanyAdmin } from "./permissions.js";
import { onAuthStateChanged } from "https://www.gstatic.com/firebasejs/11.10.0/firebase-auth.js";
import { collection, doc, getDocs, getDoc, updateDoc, setDoc, query, orderBy, limit, serverTimestamp } from "https://www.gstatic.com/firebasejs/11.10.0/firebase-firestore.js";
const safe=v=>String(v??"").replace(/[&<>'"]/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;","'":"&#39;",'"':"&quot;"}[c]));
const fmt=v=>v?.toDate?.()?.toLocaleString?.()||(v?new Date(v).toLocaleString():"—");
let session=null;
function toast(message,error=false){let x=document.getElementById("nlCustomerToast");if(!x){x=document.createElement("div");x.id="nlCustomerToast";document.body.appendChild(x)}x.textContent=message;x.className=`nl-customer-toast show ${error?'error':''}`;clearTimeout(x._t);x._t=setTimeout(()=>x.className="nl-customer-toast",3200)}
function addMenu(id,label,icon,after){const menu=document.querySelector(".menu");if(!menu||menu.querySelector(`[data-section="${id}"]`))return;const li=document.createElement("li");li.dataset.section=id;li.innerHTML=`<i class="fas fa-${icon}"></i> ${label}`;if(after)menu.insertBefore(li,after.nextSibling);else menu.appendChild(li);li.addEventListener("click",()=>show(id));}
function addPage(id,title,subtitle,html){const main=document.querySelector(".main");if(!main||document.getElementById(id))return;const s=document.createElement("section");s.id=id;s.className="page nl-customer-page";s.innerHTML=`<header class="nl-customer-header"><div><span>NEWLOOK SaaS</span><h1>${title}</h1><p>${subtitle}</p></div></header>${html}`;main.appendChild(s)}
function show(id){document.querySelectorAll(".menu li").forEach(x=>x.classList.toggle("active",x.dataset.section===id));document.querySelectorAll(".page").forEach(x=>x.classList.toggle("active-page",x.id===id));if(id==='notifications')loadNotifications();if(id==='support')loadTickets();if(id==='devices')loadDevices();if(id==='settings')loadSettings()}
function addNavigation(){const anchor=document.querySelector('.menu li[data-section="broadcast"]')||document.querySelector('.menu li:last-child');if(canManageDevices(session.role)) addMenu('devices','Device Management','mobile-alt',anchor);addMenu('notifications','Notifications','bell',null);addMenu('support','Support','life-ring',null);if(isCompanyAdmin(session.role))addMenu('settings','Settings','cog',null);const payroll=document.querySelector('.menu li[data-saas-link="payroll"]');if(!payroll&&['company_admin','operations_manager'].includes(session.role)){addMenu('payroll-link','Payroll','file-invoice-dollar',null);const p=document.querySelector('[data-section="payroll-link"]');p.addEventListener('click',()=>location.href='payroll.html')} }
function buildPages(){addPage('devices','Device Management','Register and control Guard and Attendance devices for this company.',`<div class="nl-card-grid"><div class="nl-card"><div class="nl-card-title">Device lifecycle</div><p>Generate a one-time setup code, assign a site and choose Guard or Attendance.</p><div class="nl-actions"><button class="action-btn action-btn-primary" id="nlRegisterDevice">Register Device</button><button class="action-btn action-btn-secondary" id="nlRefreshDevices">Refresh</button></div></div><div class="nl-card" id="nlDeviceSummary">Loading…</div></div><div class="nl-table-wrap"><table><thead><tr><th>Device</th><th>Type</th><th>Site</th><th>Status</th><th>Registered</th><th>Actions</th></tr></thead><tbody id="nlDeviceBody"></tbody></table></div>`);
addPage('notifications','Notifications','Company announcements, billing alerts, security messages and support updates.',`<div class="nl-card"><div class="nl-actions"><button class="action-btn action-btn-secondary" id="nlRefreshNotifications">Refresh</button><button class="action-btn action-btn-secondary" id="nlMarkAll">Mark all read</button></div><div id="nlNotificationList"></div></div>`);
addPage('support','Support','Open and track requests with the NEWLOOK platform team.',`<div class="nl-card"><div class="nl-form-grid"><label>Subject<input id="nlSupportSubject" maxlength="120"></label><label>Priority<select id="nlSupportPriority"><option>normal</option><option>high</option><option>urgent</option></select></label><label class="wide">Message<textarea id="nlSupportMessage" maxlength="4000"></textarea></label></div><div class="nl-actions"><button class="action-btn action-btn-primary" id="nlCreateTicket">Create Ticket</button><button class="action-btn action-btn-secondary" id="nlRefreshTickets">Refresh</button></div></div><div id="nlTicketList"></div>`);
if(isCompanyAdmin(session.role))addPage('settings','Company Settings','Maintain customer workspace identity and permitted company preferences.',`<div class="nl-card"><div class="nl-form-grid"><label>Company name<input id="nlCompanyName"></label><label>Contact email<input id="nlCompanyEmail" type="email"></label><label>Phone<input id="nlCompanyPhone"></label><label>Address<input id="nlCompanyAddress"></label></div><div class="nl-actions"><button class="action-btn action-btn-primary" id="nlSaveSettings">Save Settings</button><button class="action-btn action-btn-secondary" id="nlReloadSettings">Reload</button></div></div><div class="nl-card" id="nlPlanCard"></div>`);
}
async function loadDevices(){const body=document.getElementById('nlDeviceBody');if(!body)return;try{const s=await getDocs(companyCollection(db,'devices'));let active=0,guard=0,attendance=0;body.innerHTML=s.docs.map(d=>{const x=d.data();const type=String(x.deviceType||'guard').toLowerCase();if(x.status==='active')active++;if(type==='guard')guard++;if(type==='attendance')attendance++;return `<tr><td><strong>${safe(x.deviceName||'NEWLOOK Device')}</strong><small>${safe(x.authUid||d.id)}</small></td><td>${safe(type)}</td><td>${safe(x.siteName||x.siteId||'—')}</td><td><span class="nl-pill ${safe(x.status||'unknown')}">${safe(x.status||'unknown')}</span></td><td>${safe(fmt(x.registeredAt))}</td><td>${canManageDevices(session.role)?`<button class="action-btn ${x.status==='active'?'action-btn-danger':'action-btn-success'} nl-device-toggle" data-id="${safe(d.id)}" data-next="${x.status==='active'?'revoked':'active'}">${x.status==='active'?'Revoke':'Activate'}</button>`:'View only'}</td></tr>`}).join('')||'<tr><td colspan="6" class="nl-empty">No devices registered.</td></tr>';document.getElementById('nlDeviceSummary').innerHTML=`<div class="nl-card-title">Fleet status</div><div class="nl-stats"><b>${active}<small>Active</small></b><b>${guard}<small>Guard</small></b><b>${attendance}<small>Attendance</small></b></div>`;body.querySelectorAll('.nl-device-toggle').forEach(b=>b.onclick=async()=>{if(!confirm(`${b.dataset.next==='revoked'?'Revoke':'Activate'} this device?`))return;try{await updateDoc(doc(db,'companies',getCompanyId(),'devices',b.dataset.id),{status:b.dataset.next,updatedAt:serverTimestamp()});toast('Device updated');loadDevices()}catch(e){toast(e.message,true)}})}catch(e){body.innerHTML=`<tr><td colspan="6">${safe(e.message)}</td></tr>`}}
async function loadNotifications(){const box=document.getElementById('nlNotificationList');if(!box)return;try{const s=await getDocs(query(companyCollection(db,'notifications'),orderBy('createdAt','desc'),limit(80)));box.innerHTML=s.docs.map(d=>{const x=d.data();const read=Boolean(x.read || x.readBy?.[auth.currentUser?.uid]);return `<article class="nl-notification ${read?'read':''}"><div><strong>${safe(x.title||'Notification')}</strong><p>${safe(x.message||'')}</p><small>${safe(x.type||'info')} · ${safe(fmt(x.createdAt))}</small></div>${read?'':'<button class="action-btn action-btn-secondary nl-read" data-id="'+safe(d.id)+'">Mark read</button>'}</article>`}).join('')||'<div class="nl-empty">No notifications.</div>';box.querySelectorAll('.nl-read').forEach(b=>b.onclick=async()=>{await updateDoc(doc(db,'companies',getCompanyId(),'notifications',b.dataset.id),{[`readBy.${auth.currentUser.uid}`]:true,updatedAt:serverTimestamp()});loadNotifications()})}catch(e){box.innerHTML=`<div class="nl-empty">${safe(e.message)}</div>`}}
async function loadTickets(){const box=document.getElementById('nlTicketList');if(!box)return;try{const s=await getDocs(query(companyCollection(db,'supportTickets'),orderBy('createdAt','desc'),limit(50)));box.innerHTML=s.docs.map(d=>{const x=d.data();return `<article class="nl-ticket"><div class="nl-ticket-head"><strong>${safe(x.subject||'Untitled')}</strong><span>${safe(x.status||'open')}</span><span>${safe(x.priority||'normal')}</span></div><p>${safe(x.message||'')}</p>${x.response?`<div class="nl-response"><strong>NEWLOOK Support</strong><p>${safe(x.response)}</p><small>${safe(fmt(x.respondedAt))}</small></div>`:''}<small>Created ${safe(fmt(x.createdAt))}</small>${x.createdBy===auth.currentUser?.uid&&String(x.status||'').toLowerCase()!=='closed'?`<button class="action-btn action-btn-secondary nl-follow" data-id="${safe(d.id)}">Add follow-up</button>`:''}</article>`}).join('')||'<div class="nl-empty">No support tickets.</div>';box.querySelectorAll('.nl-follow').forEach(b=>b.onclick=async()=>{const message=prompt('Add follow-up message');if(!message?.trim())return;const old=s.docs.find(d=>d.id===b.dataset.id)?.data()?.message||'';await updateDoc(doc(db,'companies',getCompanyId(),'supportTickets',b.dataset.id),{message:`${old}\n\nFollow-up: ${message.trim()}`,updatedAt:serverTimestamp()});loadTickets()})}catch(e){box.innerHTML=`<div class="nl-empty">${safe(e.message)}</div>`}}
async function createTicket(){const subject=document.getElementById('nlSupportSubject').value.trim(),message=document.getElementById('nlSupportMessage').value.trim(),priority=document.getElementById('nlSupportPriority').value;if(!subject||!message)return toast('Enter a subject and message.',true);try{const r=companyDoc(companyCollection(db,'supportTickets'));await setDoc(r,{ticketId:r.id,companyId:getCompanyId(),companyName:session.companyName||'',subject,message,priority,status:'open',createdBy:auth.currentUser.uid,createdByEmail:auth.currentUser.email||'',createdAt:serverTimestamp(),updatedAt:serverTimestamp()});toast('Support ticket created');document.getElementById('nlSupportSubject').value='';document.getElementById('nlSupportMessage').value='';loadTickets()}catch(e){toast(e.message,true)}}
async function loadSettings(){if(!isCompanyAdmin(session.role))return;try{const c=session;document.getElementById('nlCompanyName').value=c.companyName||'';document.getElementById('nlCompanyEmail').value=c.email||'';document.getElementById('nlCompanyPhone').value='';document.getElementById('nlCompanyAddress').value='';const snap=await getDoc(doc(db,'companies',getCompanyId()));if(snap.exists()){const x=snap.data();document.getElementById('nlCompanyName').value=x.name||x.companyName||'';document.getElementById('nlCompanyEmail').value=x.contactEmail||'';document.getElementById('nlCompanyPhone').value=x.phone||'';document.getElementById('nlCompanyAddress').value=x.address||'';document.getElementById('nlPlanCard').innerHTML=`<div class="nl-card-title">Current plan</div><p><strong>${safe(x.planId||'Not assigned')}</strong> · ${safe(x.subscriptionStatus||'unknown')}</p><small>Expires: ${safe(fmt(x.subscriptionEndsAt))}</small>`}}catch(e){toast(e.message,true)}}
async function saveSettings(){try{await updateDoc(doc(db,'companies',getCompanyId()),{name:document.getElementById('nlCompanyName').value.trim(),companyName:document.getElementById('nlCompanyName').value.trim(),contactEmail:document.getElementById('nlCompanyEmail').value.trim(),phone:document.getElementById('nlCompanyPhone').value.trim(),address:document.getElementById('nlCompanyAddress').value.trim(),updatedAt:serverTimestamp()});toast('Company settings saved');await loadSettings()}catch(e){toast(e.message,true)}}
function wire(){document.getElementById('nlRegisterDevice')?.addEventListener('click',()=>location.href='device-registration.html');document.getElementById('nlRefreshDevices')?.addEventListener('click',loadDevices);document.getElementById('nlRefreshNotifications')?.addEventListener('click',loadNotifications);document.getElementById('nlMarkAll')?.addEventListener('click',async()=>{const s=await getDocs(query(companyCollection(db,'notifications'),limit(80)));await Promise.all(s.docs.filter(d=>!d.data().readBy?.[auth.currentUser.uid] && !d.data().read).map(d=>updateDoc(d.ref,{[`readBy.${auth.currentUser.uid}`]:true,updatedAt:serverTimestamp()})));loadNotifications()});document.getElementById('nlCreateTicket')?.addEventListener('click',createTicket);document.getElementById('nlRefreshTickets')?.addEventListener('click',loadTickets);document.getElementById('nlSaveSettings')?.addEventListener('click',saveSettings);document.getElementById('nlReloadSettings')?.addEventListener('click',loadSettings)}
onAuthStateChanged(auth,async user=>{if(!user)return;try{session=await loadSession(user);if(!session.companyId)return;addNavigation();buildPages();wire()}catch(e){console.error('Customer SaaS control',e)}});
