import { auth, db, firebaseConfig } from "./Js/firebase.js";
import { clearSession } from "./SaaS/companySession.js";
import { initializeApp, deleteApp } from "https://www.gstatic.com/firebasejs/11.10.0/firebase-app.js";
import { getAuth, createUserWithEmailAndPassword, signOut as secondarySignOut } from "https://www.gstatic.com/firebasejs/11.10.0/firebase-auth.js";
import { onAuthStateChanged } from "https://www.gstatic.com/firebasejs/11.10.0/firebase-auth.js";
import { collection, doc, getDocs, setDoc, updateDoc, query, where, serverTimestamp } from "https://www.gstatic.com/firebasejs/11.10.0/firebase-firestore.js";
import { loadSession } from "./SaaS/companySession.js";
import { isCompanyAdmin, normalizeRole } from "./SaaS/permissions.js";
const logout=document.getElementById("logout");
if(logout) logout.onclick=async()=>{await import("https://www.gstatic.com/firebasejs/11.10.0/firebase-auth.js").then(m=>m.signOut(auth));clearSession();location.href="SaasLogin.html"};
const rows=document.getElementById("rows"),modal=document.getElementById("modal"),form=document.getElementById("form"),message=document.getElementById("message");let session;
const esc=x=>String(x??"").replace(/[&<>'"]/g,s=>({"&":"&amp;","<":"&lt;",">":"&gt;","'":"&#39;","\"":"&quot;"}[s]));
async function load(){const snap=await getDocs(query(collection(db,"users"),where("companyId","==",session.companyId)));const list=snap.docs.map(d=>({id:d.id,...d.data()}));rows.innerHTML=list.length?list.map(u=>`<tr><td>${esc(u.fullName||u.displayName)}</td><td>${esc(u.email)}</td><td>${esc(normalizeRole(u.role))}</td><td><span class="pill">${esc(u.status||"active")}</span></td><td>${normalizeRole(u.role)!=="company_admin"?`<button data-id="${u.id}" data-next="${String(u.status||"active").toLowerCase()==="active"?"suspended":"active"}">${String(u.status||"active").toLowerCase()==="active"?"Suspend":"Activate"}</button>`:"Protected"}</td></tr>`).join(""):"<tr><td colspan=5>No management users yet.</td></tr>";rows.querySelectorAll("button[data-id]").forEach(b=>b.onclick=async()=>{await updateDoc(doc(db,"users",b.dataset.id),{status:b.dataset.next,updatedAt:serverTimestamp()});load();});}
document.getElementById("addUser").onclick=()=>{message.textContent="";modal.classList.remove("hidden")};document.getElementById("close").onclick=()=>modal.classList.add("hidden");form.onsubmit=async e=>{e.preventDefault();message.textContent="Creating…";const data=Object.fromEntries(new FormData(form));let app;try{app=initializeApp(firebaseConfig,`newlook-user-${Date.now()}`);const a=getAuth(app);const cred=await createUserWithEmailAndPassword(a,data.email.trim(),data.password);await setDoc(doc(db,"users",cred.user.uid),{email:data.email.trim(),fullName:data.fullName.trim(),displayName:data.fullName.trim(),role:data.role,companyId:session.companyId,status:"active",createdAt:serverTimestamp(),updatedAt:serverTimestamp(),createdBy:auth.currentUser.uid});await secondarySignOut(a);form.reset();modal.classList.add("hidden");await load();}catch(err){message.textContent=err.message||"Unable to create user.";}finally{try{if(app)await deleteApp(app)}catch{}}};
onAuthStateChanged(auth,async user=>{if(!user)return location.href="SaasLogin.html";try{session=await loadSession(user);if(!isCompanyAdmin(session.role))throw Error("Company Admin access required.");await load();}catch(e){console.error(e);location.href="SaasLogin.html";}});
