import { db } from '../Js/firebase.js';
import { getDocs, collection, query, limit, orderBy } from 'https://www.gstatic.com/firebasejs/11.10.0/firebase-firestore.js';
const app=document.getElementById('app');
const esc=v=>String(v??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
const rows=async(path,n=100)=>{try{const s=await getDocs(query(collection(db,...path),limit(n)));return s.docs.map(d=>({id:d.id,...d.data()}))}catch{return[]}};
const table=(h,r,e='No data available.')=>`<div class="table"><table><thead><tr>${h.map(x=>`<th>${x}</th>`).join('')}</tr></thead><tbody>${r||`<tr><td colspan="${h.length}" class="empty">${e}</td></tr>`}</tbody></table></div>`;
const metric=(l,v,h='')=>`<div class="card metric"><div class="label">${l}</div><div class="value">${v}</div><div class="hint">${h}</div></div>`;
const date=v=>v?.toDate?.()?.toLocaleString?.()||'—';
const defs=[
 ['success','Customer Success','hand-holding-heart','Customer health, engagement and support workload.'],
 ['onboarding','Onboarding Center','rocket','Customer activation and onboarding readiness.'],
 ['service','Service Management','screwdriver-wrench','Platform service requests and operational ownership.'],
 ['data-management','Data Management','database','Tenant data inventory and governance visibility.'],
 ['backup','Backup & Recovery','database','Backup and recovery readiness controls.'],
 ['api-integrations','API & Integrations','plug','Integration readiness and connected service registry.'],
 ['communications','Email & Communications','envelope','Platform announcements and communication activity.'],
 ['automation','Platform Automation','bolt','Automation policies and scheduled operational jobs.'],
 ['system-logs','System Logs','file-lines','Platform-wide administrative and system event review.']
];
function addNav(){const nav=document.querySelector('nav');defs.forEach(([id,label])=>{if(nav?.querySelector(`[data-v="${id}"]`))return;const b=document.createElement('button');b.dataset.v=id;b.className='action-btn action-btn-secondary';b.textContent=label;nav?.appendChild(b);b.onclick=()=>{nav.querySelectorAll('button').forEach(x=>x.classList.remove('active'));b.classList.add('active');window.__NEWLOOK_SUPER_ADVANCED__?.render(id)}})}
async function render(id){const fn={success:success,onboarding:onboarding,service:service,dataManagement:dataManagement,backup:backup,apiIntegrations:apiIntegrations,communications:communications,automation:automation,systemLogs:systemLogs}[id];if(fn)await fn()}
function setHeader(t,s){document.getElementById('title').textContent=t;document.getElementById('subtitle').textContent=s}
async function success(){setHeader('Customer Success','Customer health, support demand and public enquiries.');const cs=await rows(['companies']);const tickets=[];for(const c of cs.slice(0,100)){const x=await rows(['companies',c.id,'supportTickets'],30);tickets.push(...x.map(t=>({...t,company:c.name||c.companyName||c.id})))}const leads=await rows(['publicLeads'],100);app.innerHTML=`<section class="grid">${metric('Customers',cs.length)}${metric('Open support',tickets.filter(x=>String(x.status||'open')!=='closed').length)}${metric('Active tenants',cs.filter(x=>String(x.status||'active')==='active').length)}${metric('New enquiries',leads.filter(x=>String(x.status||'new')==='new').length)}</section>${table(['Company','Ticket','Priority','Status'],tickets.slice(0,35).map(x=>`<tr><td>${esc(x.company)}</td><td>${esc(x.subject||x.id)}</td><td>${esc(x.priority||'normal')}</td><td>${esc(x.status||'open')}</td></tr>`).join(''), 'No support tickets.')}${table(['Received','Name','Company','Type','Email','Message'],leads.slice(0,30).map(x=>`<tr><td>${esc(date(x.createdAt))}</td><td>${esc(x.name)}</td><td>${esc(x.company||'—')}</td><td>${esc(x.type)}</td><td>${esc(x.email)}</td><td>${esc(x.message)}</td></tr>`).join(''), 'No public enquiries.')}`}
async function onboarding(){setHeader('Onboarding Center','Customer activation and platform readiness.');const cs=await rows(['companies']);app.innerHTML=table(['Company','Status','Plan','Subscription','Onboarding'],cs.map(c=>`<tr><td>${esc(c.name||c.companyName||c.id)}</td><td>${esc(c.status||'active')}</td><td>${esc(c.planId||'—')}</td><td>${esc(c.subscriptionStatus||'active')}</td><td><span class="pill active">Tenant provisioned</span></td></tr>`).join(''))}
async function service(){setHeader('Service Management','Support queue and service ownership.');const cs=await rows(['companies']);const t=[];for(const c of cs.slice(0,100)){const x=await rows(['companies',c.id,'supportTickets'],50);t.push(...x.map(v=>({...v,company:c.name||c.companyName||c.id})))}app.innerHTML=table(['Created','Company','Subject','Priority','Status'],t.map(x=>`<tr><td>${esc(date(x.createdAt))}</td><td>${esc(x.company)}</td><td>${esc(x.subject||'—')}</td><td>${esc(x.priority||'normal')}</td><td>${esc(x.status||'open')}</td></tr>`).join(''))}
async function dataManagement(){setHeader('Data Management','Tenant data governance and inventory visibility.');const cs=await rows(['companies']);app.innerHTML=table(['Tenant','Company ID','Plan','Status'],cs.map(c=>`<tr><td>${esc(c.name||c.companyName||c.id)}</td><td>${esc(c.id)}</td><td>${esc(c.planId||'—')}</td><td>${esc(c.status||'active')}</td></tr>`).join(''))}
async function backup(){setHeader('Backup & Recovery','Recovery readiness without destructive operations.');const cs=await rows(['companies']);app.innerHTML=`<section class="grid">${metric('Tenants covered',cs.length,'Logical tenant inventory')}${metric('Recovery mode','Manual','No Cloud Functions used')}${metric('Storage','Firestore','Primary data source')}</section><div class="card"><h3>Recovery policy</h3><p class="muted">This release provides recovery visibility and tenant inventory. Automated backups are not falsely represented as active.</p></div>`}
async function apiIntegrations(){setHeader('API & Integrations','Integration registry and readiness.');const cs=await rows(['companies']);app.innerHTML=`<section class="grid">${metric('Tenants',cs.length)}${metric('API layer','Ready','Application-controlled')} ${metric('Webhooks','External','Provider dependent')}</section>${table(['Integration Domain','State','Notes'],`<tr><td>Firebase</td><td>Connected</td><td>Authentication and Firestore</td></tr><tr><td>Payments</td><td>Provider-ready</td><td>Connect PayFast/Peach when configured</td></tr><tr><td>Email</td><td>Application-ready</td><td>Provider configuration required</td></tr>` )}`}
async function communications(){setHeader('Email & Communications','Platform notification and announcement activity.');const n=await rows(['superAdminNotifications'],100);app.innerHTML=table(['Title','Type','Created'],n.map(x=>`<tr><td>${esc(x.title||'Announcement')}</td><td>${esc(x.type||'info')}</td><td>${esc(date(x.createdAt))}</td></tr>`).join(''))}
async function automation(){setHeader('Platform Automation','Automation policy registry and execution readiness.');app.innerHTML=`<section class="grid">${metric('Scheduled jobs','0','No background scheduler claimed')}${metric('Cloud Functions','Disabled','Project constraint')}${metric('Manual controls','Available','Admin-triggered workflows')}</section><div class="card"><h3>Automation boundary</h3><p class="muted">No automated job is represented as live unless it exists in the application. This prevents false production-health claims.</p></div>`}
async function systemLogs(){setHeader('System Logs','Administrative and tenant activity review.');const cs=await rows(['companies']);const all=[];for(const c of cs.slice(0,60)){const a=await rows(['companies',c.id,'auditLogs'],50);all.push(...a.map(x=>({...x,company:c.name||c.companyName||c.id})))}all.sort((a,b)=>(b.createdAt?.toMillis?.()||0)-(a.createdAt?.toMillis?.()||0));app.innerHTML=table(['Time','Company','Action','Actor','Description'],all.slice(0,100).map(x=>`<tr><td>${esc(date(x.createdAt))}</td><td>${esc(x.company)}</td><td>${esc(x.action||'Activity')}</td><td>${esc(x.performedByEmail||x.performedBy||'—')}</td><td>${esc(x.description||'')}</td></tr>`).join(''))}
window.__NEWLOOK_SUPER_ADVANCED__={render};addNav();
